import Image from "next/image";
import profileImg from "../images/profile.png";

export default function MediaOptimizationPage() {
  return (
    <div>
      <h1>Media Optimization (F-210)</h1>

      <section>
        <h2>Static import — automatic width/height/blurDataURL</h2>
        {/* No width/height passed -- Next.js reads them from the real
            400x300 PNG generated by scripts/make-png.mjs. preload
            replaces the deprecated (as of v16) priority prop. */}
        <Image src={profileImg} alt="Static-imported profile" preload placeholder="blur" />
      </section>

      <section>
        <h2>Local path (public/) — explicit width/height, quality=90</h2>
        {/* quality=90 -- real test of this version's `qualities` allowlist,
            which defaults to [75] only as of v16. */}
        <Image src="/hero.png" alt="Local hero" width={600} height={315} quality={90} />
      </section>

      <section>
        <h2>Remote image — unconfigured host, real remotePatterns test</h2>
        <Image
          src="https://httpbin.org/image/jpeg"
          alt="Remote unconfigured"
          width={300}
          height={200}
        />
      </section>
    </div>
  );
}
