/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import org.openapitools.client.ApiClient;
/**
 * OrderDto
 */
@JsonPropertyOrder({
  OrderDto.JSON_PROPERTY_ID,
  OrderDto.JSON_PROPERTY_CUSTOMER_NAME,
  OrderDto.JSON_PROPERTY_AMOUNT_CENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-18T15:46:12.012837-06:00[America/Mexico_City]", comments = "Generator version: 7.25.0")
public class OrderDto {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_CUSTOMER_NAME = "customerName";
  @javax.annotation.Nullable
  private String customerName;

  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amountCents";
  @javax.annotation.Nullable
  private Long amountCents;

  public OrderDto() { 
  }

  public OrderDto id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public OrderDto customerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
    return this;
  }

  /**
   * Get customerName
   * @return customerName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCustomerName() {
    return customerName;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomerName(@javax.annotation.Nullable String customerName) {
    this.customerName = customerName;
  }


  public OrderDto amountCents(@javax.annotation.Nullable Long amountCents) {
    this.amountCents = amountCents;
    return this;
  }

  /**
   * Get amountCents
   * @return amountCents
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AMOUNT_CENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getAmountCents() {
    return amountCents;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT_CENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountCents(@javax.annotation.Nullable Long amountCents) {
    this.amountCents = amountCents;
  }


  /**
   * Return true if this OrderDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderDto orderDto = (OrderDto) o;
    return Objects.equals(this.id, orderDto.id) &&
        Objects.equals(this.customerName, orderDto.customerName) &&
        Objects.equals(this.amountCents, orderDto.amountCents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, customerName, amountCents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    customerName: ").append(toIndentedString(customerName)).append("\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `customerName` to the URL query string
    if (getCustomerName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scustomerName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCustomerName()))));
    }

    // add `amountCents` to the URL query string
    if (getAmountCents() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%samountCents%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAmountCents()))));
    }

    return joiner.toString();
  }
}

