#!/usr/bin/env python3
"""Builds docs/assets/pack-schedule-index.json: for every syllabus/ chapter,
which study-pack week(s) actually link to it.

This is the data source for docs/javascripts/chapter-context.js's "Scheduled
in" box -- deliberately just a reverse index of real, already-authored
markdown links (study-packs/**/README.md -> syllabus/**/*.md), not a
computed "next chapter in your path" suggestion. A learning path only names
2-4 priority topics per domain, not an exhaustive per-chapter ordering, so
inventing a specific "next" chapter would risk asserting a sequence this
repository's own source material doesn't actually define. What every week's
README *does* define, unambiguously, is which chapters it schedules -- that
real fact is what this indexes.

Output is intentionally NOT checked into git (see .gitignore) -- it's
regenerated by scripts/build_docs_site.sh every run, the same treatment as
the docs/<dir>/ mirrors it's built from.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
STUDY_PACKS = REPO_ROOT / "study-packs"
OUTPUT = REPO_ROOT / "docs" / "assets" / "pack-schedule-index.json"

# study-packs/<dir>/ track slug -> display name. Small, hand-maintained list
# (8 real programs, per study-packs/README.md) rather than derived from
# directory-name string manipulation, since "mid-to-senior" -> "Mid To
# Senior" loses the real "→" arrow every program's own README uses.
PACK_LABELS = {
    "junior-to-mid": "Junior → Mid",
    "mid-to-senior": "Mid → Senior",
    "senior-to-staff": "Senior → Staff",
    "backend-java-specialization": "Backend Java Specialization",
    "frontend-junior-to-mid": "Frontend Junior → Mid",
    "frontend-mid-to-senior": "Frontend Mid → Senior",
    "interview-emergency-sprint": "Interview Emergency Sprint",
}

LINK_RE = re.compile(r"\]\(([^)\s]+\.md)\)")


def resolve_link(readme_path: Path, target: str) -> Path | None:
    """Resolve a markdown link target relative to readme_path to a real
    repo-root-relative path, or None if it doesn't point at a real file."""
    if target.startswith(("http://", "https://", "#")):
        return None
    resolved = (readme_path.parent / target).resolve()
    try:
        rel = resolved.relative_to(REPO_ROOT)
    except ValueError:
        return None
    return rel


def week_meta(readme_path: Path) -> tuple[int | None, str | None]:
    """Pull `week:` and `title:` straight out of the front matter block --
    avoids a YAML dependency for two scalar fields."""
    text = readme_path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None, None
    end = text.find("\n---", 3)
    front = text[3:end] if end != -1 else ""
    week_match = re.search(r'^week:\s*(\d+)\s*$', front, re.MULTILINE)
    title_match = re.search(r'^title:\s*"?(.+?)"?\s*$', front, re.MULTILINE)
    week = int(week_match.group(1)) if week_match else None
    title = title_match.group(1) if title_match else None
    return week, title


def main() -> int:
    index: dict[str, list[dict]] = {}

    # Named tracks: study-packs/<track>/week-NN/README.md
    for track_dir in sorted(STUDY_PACKS.iterdir()):
        if not track_dir.is_dir():
            continue
        track_slug = track_dir.name
        if track_slug.startswith("week-"):
            continue  # handled by the flat-sprint branch below
        for week_dir in sorted(track_dir.glob("week-*")):
            readme = week_dir / "README.md"
            if not readme.is_file():
                continue
            week_num, week_title = week_meta(readme)
            _index_readme(readme, track_slug, week_num, week_title, index)

    # Interview Emergency Sprint: flat study-packs/week-NN/README.md
    for week_dir in sorted(STUDY_PACKS.glob("week-*")):
        readme = week_dir / "README.md"
        if not readme.is_file():
            continue
        week_num, week_title = week_meta(readme)
        _index_readme(readme, "interview-emergency-sprint", week_num, week_title, index)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(index, indent=0, sort_keys=True), encoding="utf-8")
    total_links = sum(len(v) for v in index.values())
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}: {len(index)} chapters, {total_links} pack/week references")
    return 0


def _index_readme(readme: Path, track_slug: str, week_num, week_title, index: dict) -> None:
    text = readme.read_text(encoding="utf-8")
    seen_this_week: set[str] = set()
    for target in LINK_RE.findall(text):
        resolved = resolve_link(readme, target)
        if resolved is None:
            continue
        if resolved.parts[0] != "syllabus":
            continue
        if resolved.name in ("INDEX.md", "changelog.md"):
            continue
        key = resolved.as_posix()
        if key in seen_this_week:
            continue
        seen_this_week.add(key)
        entry = {
            "pack": PACK_LABELS.get(track_slug, track_slug),
            "week": week_num,
            "url": _week_url(readme),
        }
        index.setdefault(key, []).append(entry)


def _week_url(readme: Path) -> str:
    """Site-base-relative URL for this week's page, e.g.
    study-packs/mid-to-senior/week-13/ -- deliberately no leading slash:
    the site can be deployed under a subpath (GitHub Pages project site),
    so the consuming JS resolves this against its own detected base URL
    rather than the domain root."""
    week_dir = readme.parent.relative_to(REPO_ROOT)
    return week_dir.as_posix() + "/"


if __name__ == "__main__":
    sys.exit(main())
